// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: examples/nested.proto

package validatorexamples

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/lucianoapolo/go-proto-validators"
	regexp "regexp"
	github_com_lucianoapolo_go_proto_validators "github.com/lucianoapolo/go-proto-validators"
	google_golang_org_genproto_googleapis_rpc_errdetails "google.golang.org/genproto/googleapis/rpc/errdetails"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *InnerMessage) Validate() []*google_golang_org_genproto_googleapis_rpc_errdetails.BadRequest_FieldViolation {
	fieldsViolations := []*google_golang_org_genproto_googleapis_rpc_errdetails.BadRequest_FieldViolation{}
	if !(this.SomeInteger > 0) {
		fieldViolation := &google_golang_org_genproto_googleapis_rpc_errdetails.BadRequest_FieldViolation{Field: "SomeInteger", Description: fmt.Sprintf(`valor '%v' deve ser maior que '0'`, this.SomeInteger)}
		fieldsViolations = append(fieldsViolations, fieldViolation)
	}
	if !(this.SomeInteger < 100) {
		fieldViolation := &google_golang_org_genproto_googleapis_rpc_errdetails.BadRequest_FieldViolation{Field: "SomeInteger", Description: fmt.Sprintf(`valor '%v' deve ser menor que '100'`, this.SomeInteger)}
		fieldsViolations = append(fieldsViolations, fieldViolation)
	}
	if len(fieldsViolations) > 0 {
		return fieldsViolations
	} else {
		return nil
	}
}

var _regex_OuterMessage_ImportantString_00 = regexp.MustCompile(`^[a-z]{2,5}$`)

func (this *OuterMessage) Validate() []*google_golang_org_genproto_googleapis_rpc_errdetails.BadRequest_FieldViolation {
	fieldsViolations := []*google_golang_org_genproto_googleapis_rpc_errdetails.BadRequest_FieldViolation{}
	if !_regex_OuterMessage_ImportantString_00.MatchString(this.ImportantString) {
		fieldViolation := &google_golang_org_genproto_googleapis_rpc_errdetails.BadRequest_FieldViolation{Field: "ImportantString", Description: fmt.Sprintf(`valor '%v' deve estar em conformidade com regex "^[a-z]{2,5}$"`, this.ImportantString)}
		fieldsViolations = append(fieldsViolations, fieldViolation)
	}
	if nil == this.Inner {
		fieldViolation := &google_golang_org_genproto_googleapis_rpc_errdetails.BadRequest_FieldViolation{Field: "Inner", Description: `os dados devem ser preenchidos`}
		fieldsViolations = append(fieldsViolations, fieldViolation)
	}
	if this.Inner != nil {
		if fieldsViolationsChild := github_com_lucianoapolo_go_proto_validators.CallValidatorIfExists(this.Inner); fieldsViolationsChild != nil {
			fieldsViolations = append(fieldsViolations, fieldsViolationsChild...)
		}
	}
	if len(fieldsViolations) > 0 {
		return fieldsViolations
	} else {
		return nil
	}
}
